version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_notification
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data_notification
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # если нужен init.sql

volumes:
  pgdata: